### ISSUE TITLE
Code Review voor Karin, door Ralf - 29 maart 2020

### ISSUE THREAD

**Issue by ralfz123** [KarinMeijvogel/datingapp#3]
name: Week 7 - Code review
about: Code review on a classmate
title: Code review
labels: 'week-7, week-7-code-review'

# Code review

## Name
Ralf Zonneveld
## Class
tech-1
## Feedback
Installatie ging heel soepel.  
Na de .env file content gevraagd te hebben, werkt het in de localhost:3000 goed. Alles is klikbaar en er zit in een logische structuur in het gebruik van de app. Je kan nu alleen nog kiezen uit een aantal profielen en daarmee kan je door naar de app (liken/matchen). Ik neem aan dat dat kiezen van een profiel wordt vervangen door inloggen en registreren van een account. Maar dat is natuurlijk nu nog niet aan de orde. Al met al, een fijne en clear interface van de app👌.

Wat betreft de code:  
Server (index.js).  
Bij elk stuk code staat in comments waar dat stuk code over gaat. Ook is er een 'line' aangebracht in de comments waardoor het overzichtelijk wordt. Wat ik zelf niet gewend ben, maar wat Karin wel doet, is dat de 'app.' van alle onderwerpen (static folder, session en handle routes) **niet** bij elkaar staan. Ik vind het persoonlijk overzichtelijker als alle 'app.' onder elkaar staan. Maar omdat Karin ze heeft 'gelabeld' met waar elk stuk code over gaat, snap ik dat wel.  
Bovendien vind ik het nice dat onder de handle routes alle functions genest zijn uitgewerkt. Dit zorgt voor nog steeds duidelijke overzichtelijkheid van de code. Ook hier is in comments gezet wat bepaalde stukken code doen.  

package.json. 
Clean file met alleen de broodnodige dependencies erin. Ik mis hier wel een linter...[ESlint](https://eslint.org/docs/user-guide/getting-started) zou ik aanraden, omdat die goed configureerbaar is.

.ejs files. 
Goed gebruik gemaakt van loops en de .ejs 'includes' (<% , <%- , <%=). .ejs files zijn mooi genest (Beautify denk ik?) en dus overzichtelijk. 

script files.  
De client-side JavaScript bestanden zijn netjes opgebouwd. Eerst declaration variables, dan functions en als laatst eventlisteners. Hier heb ik geen tips voor, alleen maar tops. Code is bovendien netjes geschreven. Echter weet ik niet of je meerder .js files mag hebben. Voor hetzelfde geldt voor meerdere .css bestanden.

Kortom, nette feature die overzichtelijke code bevat en hier en daar wat betreft linting nog iets dieper op in mag gaan.

### Feedback specifiek op criterium 1 Project Tech
Git en Github wordt zeker goed gebruikt voor versiebeheer. Ook zijn er meerdere branches aangemaakt, wat het werken in Git gemakkelijker maakt.

### Feedback specifiek op criterium 2 Project Tech
Code standaarden zoals linting moet nog even research naar gedaan worden.

### Feedback specifiek op criterium 3 Project Tech
README van Karin is erg efficient. Er staat kort uitgelegd wat de feature inhoudt. Een korte weergave van de UI en dan de installatie. Ook staat de structuur van de database er in en een hele uitgebreide bronnenlijst. Super! 

### Feedback specifiek op criterium 5 Project Tech
Er moet nog wel het registreren en inloggen verwerkt worden. Maar voor zover het er nu uitziet, gaat dat zeker goed komen.  

Goed bezig!

**Comment by KarinMeijvogel** [comment]
Thanks! Inmiddels hebben we de missende features (registreren, inloggen en meer) toegevoegd. Ook hebben we ESlint gebruikt om de codestandaarden te hanteren.
