### ISSUE TITLE
Avoid wrapping entire function bodies in if statements

### ISSUE THREAD

**Issue by follywolly** [KarinMeijvogel/datingapp#5]
## Issue location
https://github.com/KarinMeijvogel/datingapp/blob/c31f76869747c91c73864b79705fd36415b8e18d/index.js#L114-L155

## Issue topics

- Code readability

## Issue description
Currently, this function logic is entirely wrapped in an if statement. This causes more indentation, which decreases code readability. 

## How to solve
Turn the check around and return early.
Instead of checking if the userid exists, check if the userid does not exist. if it doesn't exist, redirect to login. After the redirect call, put return. This makes sure the rest of the function logic won't be executed.

### Before
```js
function likedUsers(req, res, next) {
  if (userid !== null) {
    // ... entire function logic
  } else {
    res.redirect("/login");
  }
}
```
### After
```js
function likedUsers(req, res, next) {
  // or, if (!userid) {   (falsey values)
  if (userid === null) { 
    res.redirect("/login");
    return;
  }
  // ... entire function logic
}
```

## Benefits
Not only did you lose a level of indentation which improves code readability already, people can now immediately see what happens when there is no userid.

General rule: 
- if the if part is really big and the else part really small, turn the check around
- If the if statement is the top level of the function and there is no code following the if else statement, put a small if statement that returns the function early.

## Disclaimer

Please think about every opened issue and decide wether or not you want to do anything with it. It's not important to do it my way, it's important to _be able to explain what you did or didn't do with it and why_.

**Comment by KarinMeijvogel** [comment]
Followed your suggestion to turn the check around.

Now checking if the user doesn't exist at the beginning of the function, and returning if it doesn't. If the user does exist, the rest of the function gets executed and the user gets to see their pages.
