### ISSUE TITLE
Avoid global save of user

### ISSUE THREAD

**Issue by follywolly** [KarinMeijvogel/datingapp#7]
## Issue location
https://github.com/KarinMeijvogel/datingapp/blob/9dc7daa8ae5093d4f052ff9b013a2d7cb355a8ed/index.js#L23

https://github.com/KarinMeijvogel/datingapp/blob/9dc7daa8ae5093d4f052ff9b013a2d7cb355a8ed/index.js#L38-L44

## Issue topics

- Error prevention

## Issue description
You are initializing session but not doing anything with it. Also, you are saving the user globally, which is considered a bad pattern (If the server restarts, the user is gone).

## How to solve
Remove global userid variable
In login function, rewrite `userid = req.body.user;` to `req.session.user = req.body.user`.
Then write all references to `userid` to `req.session.user` 

## Benefits
- No loss of data on server reset
- No global variable that can be overwritten by accident 

## Disclaimer

Please think about every opened issue and decide wether or not you want to do anything with it. It's not important to do it my way, it's important to _be able to explain what you did or didn't do with it and why_.

**Comment by KarinMeijvogel** [comment]
Removed global userid variable. In the login function, the data of the user that's logging is retrieved from the database, and stored in the session.
